// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

function App$App(props) {
  console.log("hello kemal");
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: "Hello"
            });
}

var App = {
  make: App$App
};

var render = window.document.createElement("div");

var root = Client.createRoot(render);

root.render(JsxRuntime.jsx(App$App, {}));

export {
  App ,
  render ,
  root ,
}
/* render Not a pure module */
